### PR TITLE
Schatzsc patch 1

### PR DESCRIPTION
**Pull request by schatzsc**
More changes to current tuple format in documentation and update of element properties to also include element names

### CODE REVIEW

**Review by JanCBrammer — APPROVED** [review]

**Comment by JanCBrammer** [comment]
We're currently not using the properties `element_name` and `element_color`. Is there a future use case for those?

**Comment by schatzsc** [comment]
> We're currently not using the properties `element_name` and `element_color`. Is there a future use case for those?

`element_color` could be used in `draw_molecules` to color the nodes according to standard colors used in common viewers. The current color schemes are not in line with this.

`element_name` is used for example to directly link to Wikipedia page on the element in

[https://github.com/schatzsc/TUCAN_playground/blob/main/tucan2_main.py](url)

with `def plot_graph_with_gravis(graph):`

`click_node_template = ( `
`        'Wikipedia: <a href="https://en.wikipedia.org/wiki/{element_name}" target="_blank">click here</a>')`
`)`

From there, you could possibly "harvest" additional information to be used with custom node features.

**Comment by schatzsc** [comment]
Could you simply use `element_color` as the `highlight` instead of `atomic_number` ??? Just have to check if the hex format like `0xEB0026` is supported (and H has color `lightgrey`)

`highlight_colors = list(nx.get_node_attributes(m, highlight).values())`

**Comment by schatzsc** [comment]
Not so easy:

**node_color : _color or array of colors (default=’#1f78b4’)_**

**Node color.** Can be a single color or a sequence of colors with the same length as nodelist. **Color can be string or rgb (or rgba) tuple of floats from 0-1**. If numeric values are specified they will be mapped to colors using the cmap and vmin,vmax parameters. See matplotlib.scatter for more details.

[draw_networkx](https://networkx.org/documentation/stable/reference/generated/networkx.drawing.nx_pylab.draw_networkx.html#networkx.drawing.nx_pylab.draw_networkx)

**Pull request merged**
